version: '2'
services:

  # nginx-proxy
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"

    volumes:
      # コンテナイベントの取得のためにdocker.sockをro[Read Only]でマウント
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql

  db_api:
      build: ./Docker/flask
      # ports:
      #  - "5000:5000"
      volumes:
       - ./src/db_api/:/code
      depends_on:
       - redis
      expose:
        - "80"
      links:
        - mysql
      environment:
        VIRTUAL_HOST: db.localhost
        VIRTUAL_PORT: 80

  redis:
    image: redis

  app:
    build: ./Docker/php
    volumes:
     - ./src/php/:/var/www/html
    expose:
      - "80"
    links:
      - mysql
    environment:
      VIRTUAL_HOST: app.localhost
      VIRTUAL_PORT: 80

  mysql:
    build: ./docker/mysql
    volumes_from:
      - db_data
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: python
      MYSQL_PASSWORD: python
      MYSQL_DATABASE: question
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    # expose:
    #   - "3306"
    ports:
      - "3306"

  web:
    image: httpd:2.4
    environment:
      VIRTUAL_HOST: localhost.com, www.*, ec-supli.com
